### ISSUE TITLE
im getting 1 error allways i do node start

### ISSUE THREAD

**Issue by memendes123** [3urobeat/steam-comment-service-bot#199]
[ERROR] Unhandled Rejection Error! Reason: TypeError: Cannot read properties of undefined (reading '1')
    at Bot.handleMissingGameLicenses (C:\Users\helde\Desktop\BOTS\steam-comment-service-bot-master\src\bot\helpers\handleMissingGameLicenses.js:37:59)
    at SteamUser.<anonymous> (C:\Users\helde\Desktop\BOTS\steam-comment-service-bot-master\src\bot\events\webSession.js:143:14)
    at SteamUser.emit (node:events:512:28)
    at SteamUser._webAuthenticate (C:\Users\helde\Desktop\BOTS\steam-comment-service-bot-master\node_modules\steam-user\components\07-web.js:91:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue!  
Which games have you set in your config at `playinggames`?

**Comment by 3urobeat** [comment]
Closing as stale.  
Please re-open if you are still encountering this issue!
