### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by c5wld** [3urobeat/steam-comment-service-bot#258]
When Starting Program i get this error : 

[ERROR] Unhandled Rejection Error! Reason: TypeError: Cannot read properties of undefined (reading 'length')
    at C:\Users\matib\Desktop\steam-comment-service-bot-master\src\dataManager\dataProcessing.js:34:40
    at new Promise (<anonymous>)
    at yourgroup (C:\Users\matib\Desktop\steam-comment-service-bot-master\src\dataManager\dataProcessing.js:32:16)
    at DataManager.processData (C:\Users\matib\Desktop\steam-comment-service-bot-master\src\dataManager\dataProcessing.js:161:24)
    at Controller._start (C:\Users\matib\Desktop\steam-comment-service-bot-master\src\controller\controller.js:263:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-08-18 21:40:25 | WARN] Child Process exited with code 0! Attempting to restart...
![image](https://github.com/user-attachments/assets/543de55c-9e15-4a6d-86ab-25879d69da92)

**Comment by 3urobeat** [comment]
Hey, thanks for opening an issue.

It looks like you mangled your config, causing the bot to fail when trying to check what you set at `yourgroup`.  
Did you remove that setting by accident?

If you'd like for me to take a look at it, you can post the content of your `config.json` file here.  
Otherwise just restore it to default again and fill out the necessary settings again.

I already planned to improve checking for missing config settings to avoid a confusing error like this for new users. At the moment the bot only handles entirely corrupted configs, but in this case only one specific setting seems to be missing/broken.

**Comment by 3urobeat** [comment]
This behavior has been improved in version 2.15.4, the bot won't throw a confusing Unhandled Rejection/Exception anymore when a config value is missing.  

The mentioned missing config value handler (replacing missing property with the default setting and logging a warning) will come in version 2.16.0.

Since you didn't reply I hope you fixed your config issue and I'm going to close this issue.  
If you still need help, feel free to re-open again!
